version: '3.8'

services:
  db:
    image: mariadb:10-focal
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    healthcheck:
      test: ['CMD-SHELL', 'mysqladmin ping -h 127.0.0.1 --password="$$(cat /run/secrets/db-password)" --silent']
      interval: 3s
      retries: 5
      start_period: 30s
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backnet
    environment:
      - MYSQL_DATABASE=example
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 3306
      - 33060

  flask:
    build:
      context: flask
    restart: always
    ports:
      - 44302:80
    networks:
      - backnet
      - frontnet
    depends_on:
      - db
    environment:
      - DB_HOST=db

  nginx:
    build:
      context: nginx
    restart: always
    ports:
      - 8080:80
    networks:
      - frontnet
    depends_on: 
      - flask

volumes:
  db-data:

secrets:
  db-password:
    file: db/password.txt

networks:
  backnet:
  frontnet:
